/** Invertible book coordinate encoding.
 *
 * The target book's content is generated by a simple LCG whose initial state
 * encodes the book's coordinates. A player who reads the source can:
 *
 *   1. Read a few characters from any page of a book
 *   2. Recover the LCG state from consecutive outputs
 *   3. Reverse the state back to coordinates using the known seed
 *
 * The mapping is:
 *   coords → state:  state = mixCoords(coords) XOR seedKey
 *   state → coords:  coords = unmixCoords(state XOR seedKey)
 *
 * mixCoords/unmixCoords are a simple invertible bit-shuffle so that nearby
 * coordinates don't produce obviously similar output.
 *
 * The LCG is deliberately weak — that's the point. It's a puzzle, not crypto.
 *
 * @module invertible.core
 */

import { hash } from "./prng.core.ts";
import { BOOKS_PER_GALLERY, CHARSET_SIZE, CHARS_PER_LINE, LINES_PER_PAGE, FLOORS, POSITIONS_PER_SIDE } from "./scale.core.ts";

/* ---- Constants ---- */

const CHARSET_LEN: number = CHARSET_SIZE;

/**
 * Early-exit threshold for textToAddress.
 *
 * When converting text to a base-95 number, most texts exceed the playable
 * address space within the first few characters. This threshold lets
 * textToAddress bail out early without computing the full (potentially
 * million-digit) number.
 *
 * Set to PLAYABLE_ADDRESS_MAX — if the running total exceeds the walkable
 * library, there's no point continuing. This fires after ~9 characters
 * for random text.
 *
 * @see PLAYABLE_ADDRESS_MAX — the actual library boundary
 */
export let TEXT_ADDRESS_EARLY_EXIT: bigint;  // initialized after PLAYABLE_ADDRESS_MAX

/** @deprecated Use PLAYABLE_ADDRESS_MAX for bounds checks, TEXT_ADDRESS_EARLY_EXIT for early-exit. */
export const LIBRARY_MAX: bigint = 95n ** 66n;

/**
 * Interpret a book's text as a base-95 number and return its true address.
 * Characters are treated as digits in [0, 94] (codepoint - 32).
 *
 * Exits early if the running value exceeds `limit` — since most texts blow
 * past the early-exit threshold within the first few characters, this is nearly free
 * for out-of-bounds books.
 *
 * @param text - the book's full text (or as much as needed)
 * @param limit - stop and return current value if it exceeds this
 * @returns the address (may exceed limit if text is in bounds)
 */
export function textToAddress(text: string, limit: bigint | null = TEXT_ADDRESS_EARLY_EXIT): bigint {
    let addr = 0n;
    for (let i = 0; i < text.length; i++) {
        addr = addr * 95n + BigInt(text.charCodeAt(i) - 32);
        if (limit !== null && addr > limit) return addr;
    }
    return addr;
}

/**
 * Returns true if a book's text-as-number falls within the walkable library.
 * False means the soul is damned — their book has no shelf location.
 */
export function isInBounds(text: string): boolean {
    return textToAddress(text) <= PLAYABLE_ADDRESS_MAX;
}

/**
 * Compute a soul's book address in the coordinate system anchored to the player.
 *
 * The library's "origin" is arbitrary. We pick it by anchoring to the player:
 *   bookAddress = rawAddress - playerRawAddress + randomOrigin
 *
 * For the player themselves: rawAddress - rawAddress + randomOrigin = randomOrigin,
 * which is always within PLAYABLE_ADDRESS_MAX by construction.
 *
 * For NPCs: big number - big number + small number. Usually still enormous → damned.
 * By cosmic coincidence, an NPC whose rawAddress is close to the player's lands
 * within the library — their book genuinely exists here.
 *
 * @param rawAddress - textToAddress(storyText) for this soul, no early-exit limit
 * @param playerRawAddress - textToAddress(playerStoryText), no early-exit limit
 * @param randomOrigin - a bigint in [0, PLAYABLE_ADDRESS_MAX], derived from game seed
 * @returns bookAddress — use isAddressInBounds() to check damnation
 */
export function computeBookAddress(
    rawAddress: bigint,
    playerRawAddress: bigint,
    randomOrigin: bigint,
): bigint {
    return rawAddress - playerRawAddress + randomOrigin;
}

/**
 * Returns true if a precomputed book address maps to a reachable library location.
 * Use this (not isInBounds) when you already have the address.
 */
export function isAddressInBounds(bookAddress: bigint): boolean {
    return bookAddress >= 0n && bookAddress <= PLAYABLE_ADDRESS_MAX;
}

export { POSITIONS_PER_SIDE } from "./scale.core.ts";

/**
 * The maximum address that maps to a sensible (walkable) library location.
 * randomOrigin should be drawn from [0, PLAYABLE_ADDRESS_MAX].
 */
export const PLAYABLE_ADDRESS_MAX: bigint =
    POSITIONS_PER_SIDE * 2n * BigInt(FLOORS) * BigInt(BOOKS_PER_GALLERY); // position * sides * floors * booksPerGallery

// Now that PLAYABLE_ADDRESS_MAX is defined, set the early-exit threshold.
TEXT_ADDRESS_EARLY_EXIT = PLAYABLE_ADDRESS_MAX;

/**
 * Decompose a book address into library coordinates.
 * The address must be within [0, PLAYABLE_ADDRESS_MAX].
 *
 * Layout (innermost first):
 *   bookIndex : [0, booksPerGallery)
 *   floor     : [0, FLOORS-1]        — FLOORS floors
 *   side      : 0 or 1
 *   position  : [0, POSITIONS_PER_SIDE)
 *
 * @param addr - a bigint in [0, PLAYABLE_ADDRESS_MAX]
 * @param booksPerGallery - e.g. 200 (from scale.core.ts)
 * @returns BookCoords
 */
export function addressToCoords(addr: bigint, booksPerGallery: number): { side: number; position: bigint; floor: bigint; bookIndex: number } {
    const bpg = BigInt(booksPerGallery);
    const bookIndex = Number(addr % bpg);
    addr = addr / bpg;

    const _FLOORS = BigInt(FLOORS);
    const floor = addr % _FLOORS;
    addr = addr / _FLOORS;

    const side = Number(addr % 2n);
    const position = addr / 2n; // [0, POSITIONS_PER_SIDE)

    return { side, position, floor, bookIndex };
}

/** LCG parameters (mod 2^32). Multiplier from Numerical Recipes. */
const LCG_A: number = 1664525;
const LCG_C: number = 1013904223;

/* ---- Exported interfaces ---- */

/** Unpacked book coordinates. */
export interface BookCoords {
    side: number;
    position: number;
    floor: number;
    bookIndex: number;
}

/** LCG stream with alternating even/odd chains. */
export interface LCGStream {
    nextInt(n: number): number;
    state(): [number, number];
}

/* ---- Invertible coordinate encoding ---- */

/**
 * Pack coordinates into a single 64-bit-ish pair of 32-bit words.
 * Layout:
 *   word0: (side << 31) | ((floor & 0x7FFF) << 16) | (bookIndex & 0xFFFF)
 *   word1: position as signed int32 (reinterpreted as uint32)
 */
function packCoords(side: number, position: number, floor: number, bookIndex: number): [number, number] {
    const w0 = ((side & 1) << 31) | ((floor & 0x7FFF) << 16) | (bookIndex & 0xFFFF);
    const w1 = position | 0; // signed → int32 bits
    return [w0 >>> 0, w1 >>> 0];
}

function unpackCoords(w0: number, w1: number): BookCoords {
    const side = (w0 >>> 31) & 1;
    const floor = (w0 >>> 16) & 0x7FFF;
    const bookIndex = w0 & 0xFFFF;
    const position = w1 | 0; // reinterpret as signed
    return { side, position, floor, bookIndex };
}

/**
 * Invertible 32-bit mix (based on splitmix32 finalizer).
 * Each step is reversible.
 */
function mix32(x: number): number {
    x = x >>> 0;
    x ^= x >>> 16;
    x = Math.imul(x, 0x45d9f3b);
    x ^= x >>> 16;
    x = Math.imul(x, 0x45d9f3b);
    x ^= x >>> 16;
    return x >>> 0;
}

/** Inverse of mix32. */
function unmix32(x: number): number {
    x = x >>> 0;
    x ^= x >>> 16;
    x = Math.imul(x, 0x119de1f3); // modular inverse of 0x45d9f3b mod 2^32
    x ^= x >>> 16;
    x = Math.imul(x, 0x119de1f3);
    x ^= x >>> 16;
    return x >>> 0;
}

/**
 * Derive a 2-word key from the global seed string.
 * This is what the player needs to know (it's just hash(seed + suffix)).
 */
function seedKey(globalSeed: string): [number, number] {
    return [hash(globalSeed + ":inv0"), hash(globalSeed + ":inv1")];
}

/**
 * Encode coordinates into a 2-word LCG state.
 *
 * coords → pack → mix each word → XOR with seed key
 *
 * @param {number} side
 * @param {number} position
 * @param {number} floor
 * @param {number} bookIndex
 * @param {string} globalSeed
 * @returns {[number, number]} two uint32 state words
 */
export function encodeCoords(side: number, position: number, floor: number, bookIndex: number, globalSeed: string): [number, number] {
    const [w0, w1] = packCoords(side, position, floor, bookIndex);
    const [k0, k1] = seedKey(globalSeed);
    return [(mix32(w0) ^ k0) >>> 0, (mix32(w1) ^ k1) >>> 0];
}

/**
 * Decode a 2-word state back to coordinates.
 *
 * state → XOR with seed key → unmix each word → unpack
 *
 * @param {number} s0
 * @param {number} s1
 * @param {string} globalSeed
 * @returns {{ side, position, floor, bookIndex }}
 */
export function decodeCoords(s0: number, s1: number, globalSeed: string): BookCoords {
    const [k0, k1] = seedKey(globalSeed);
    const w0 = unmix32((s0 ^ k0) >>> 0);
    const w1 = unmix32((s1 ^ k1) >>> 0);
    return unpackCoords(w0, w1);
}

/* ---- LCG ---- */

/** Advance LCG state by one step. */
function lcgNext(s: number): number {
    return (Math.imul(LCG_A, s) + LCG_C) >>> 0;
}

/** Reverse LCG state by one step. */
// LCG_A_INV is the modular inverse of LCG_A mod 2^32.
const LCG_A_INV: number = 4276115653; // computed: LCG_A * LCG_A_INV ≡ 1 (mod 2^32)
export function lcgPrev(s: number): number {
    return Math.imul((s - LCG_C) >>> 0, LCG_A_INV) >>> 0;
}

/**
 * Create an LCG stream from a 2-word state.
 * s0 is the running LCG state. s1 is mixed in once at the start via XOR,
 * giving 64 bits of effective key space while keeping a simple 32-bit LCG
 * that's easy to reverse from output.
 *
 * Two independent LCGs read in alternation: even chars from s0, odd from s1.
 */
function makeLCG(s0: number, s1: number): LCGStream {
    let a = s0 >>> 0, b = s1 >>> 0;
    let even = true;
    return {
        nextInt(n: number): number {
            if (even) {
                a = lcgNext(a);
                even = false;
                return a % n;
            } else {
                b = lcgNext(b);
                even = true;
                return b % n;
            }
        },
        state(): [number, number] { return [a, b]; }
    };
}

/* ---- Page generation ---- */

/**
 * Generate a page of a book using the invertible LCG.
 * The state is derived from coordinates + seed, and can be reversed.
 *
 * @param {number} side
 * @param {number} position
 * @param {number} floor
 * @param {number} bookIndex
 * @param {number} pageIndex - 0-based
 * @param {string} globalSeed
 * @returns {string}
 */
export function generateTargetPage(side: number, position: number, floor: number, bookIndex: number, pageIndex: number, globalSeed: string): string {
    const [s0, s1] = encodeCoords(side, position, floor, bookIndex, globalSeed);

    // Advance LCG past prior pages to maintain determinism.
    const charsPerPage = LINES_PER_PAGE * CHARS_PER_LINE;
    const skipCalls = pageIndex * charsPerPage;
    const skipPerChain = Math.floor(skipCalls / 2);
    const extraEven = skipCalls % 2;

    let a = s0, b = s1;
    for (let i = 0; i < skipPerChain + extraEven; i++) a = lcgNext(a);
    for (let i = 0; i < skipPerChain; i++) b = lcgNext(b);

    const lcg = makeLCG(a, b);
    const lines: string[] = [];
    for (let l = 0; l < LINES_PER_PAGE; l++) {
        let line = "";
        for (let c = 0; c < CHARS_PER_LINE; c++) {
            line += String.fromCharCode(32 + lcg.nextInt(CHARSET_LEN));
        }
        lines.push(line);
    }
    return lines.join("\n");
}

/**
 * Recover coordinates from consecutive output characters of a book page.
 *
 * Requires at least 10 consecutive characters from the START of page 0.
 * (5 per chain → ~32.8 bits of constraint, uniquely pins each 32-bit state.)
 *
 * @param {string} chars - at least 10 characters from the beginning of page 0
 * @param {string} globalSeed
 * @returns {{ side, position, floor, bookIndex } | null}
 */
export function recoverCoords(chars: string, globalSeed: string): BookCoords | null {
    if (chars.length < 10) return null;

    const v: number[] = [];
    for (let i = 0; i < chars.length && i < 12; i++) {
        v.push(chars.charCodeAt(i) - 32);
    }

    const evenTargets: number[] = [];
    for (let i = 0; i < v.length; i += 2) evenTargets.push(v[i]);

    const oddTargets: number[] = [];
    for (let i = 1; i < v.length; i += 2) oddTargets.push(v[i]);

    const foundS0 = recoverOneChain(evenTargets);
    if (foundS0 === null) return null;

    const foundS1 = recoverOneChain(oddTargets);
    if (foundS1 === null) return null;

    return decodeCoords(foundS0, foundS1, globalSeed);
}

/**
 * Recover the initial state of one LCG chain given consecutive outputs mod 95.
 * targets[0] = lcgNext(s) % 95, targets[1] = lcgNext^2(s) % 95, etc.
 * Returns s, or null if no match.
 */
function recoverOneChain(targets: number[]): number | null {
    if (targets.length < 2) return null;

    for (let a = targets[0]; a < 0x100000000; a += CHARSET_LEN) {
        let match = true;
        let cur = a;
        for (let i = 1; i < targets.length; i++) {
            cur = lcgNext(cur);
            if (cur % CHARSET_LEN !== targets[i]) { match = false; break; }
        }
        if (match) return lcgPrev(a);
    }
    return null;
}

/* ---- Full-precision address computation ---- */

const _pow95Cache: Map<number, bigint> = new Map();
function _pow95(n: number): bigint {
    let p = _pow95Cache.get(n);
    if (p === undefined) {
        p = 95n ** BigInt(n);
        _pow95Cache.set(n, p);
    }
    return p;
}

function _convertRange(codes: Int32Array, start: number, end: number): bigint {
    const n = end - start;
    if (n === 0) return 0n;
    if (n === 1) return BigInt(codes[start]);
    if (n === 2) return BigInt(codes[start]) * 95n + BigInt(codes[start + 1]);
    const mid = start + (n >>> 1);
    return _convertRange(codes, start, mid) * _pow95(end - mid) + _convertRange(codes, mid, end);
}

/**
 * Full-precision textToAddress using divide-and-conquer base conversion.
 * O(n log²n) vs O(n²) for the naive Horner's method.
 *
 * Computes the true base-95 address of the full text without any early exit.
 * For 1,312,000 characters this produces a ~2.6 million digit number in ~300ms.
 *
 * Use this for verification and testing, not in hot loops.
 */
export function textToAddressFull(text: string): bigint {
    const codes = new Int32Array(text.length);
    for (let i = 0; i < text.length; i++) codes[i] = text.charCodeAt(i) - 32;
    return _convertRange(codes, 0, codes.length);
}

/* ---- Inverse: address → text (D&C) ---- */

import { CHARS_PER_BOOK } from "./scale.core.ts";

/**
 * Convert a bigint address back to a base-95 string of the given length.
 * D&C approach: divmod by 95^(n/2) splits the string into left and right
 * halves, same complexity class as textToAddressFull.
 *
 * @param addr - the bigint address
 * @param length - output string length (default CHARS_PER_BOOK)
 * @returns the base-95 decoded string
 */
export function addressToText(addr: bigint, length: number = CHARS_PER_BOOK): string {
    if (addr < 0n) throw new RangeError("addressToText: address must be non-negative");
    const buf = new Uint8Array(length);
    _fillRange(buf, 0, length, addr);
    // Convert digit values to characters
    let s = "";
    for (let i = 0; i < length; i++) s += String.fromCharCode(buf[i] + 32);
    return s;
}

function _fillRange(buf: Uint8Array, start: number, end: number, value: bigint): void {
    const n = end - start;
    if (n === 0) return;
    if (n === 1) {
        buf[start] = Number(value % 95n);
        return;
    }
    if (n === 2) {
        buf[start + 1] = Number(value % 95n);
        buf[start] = Number((value / 95n) % 95n);
        return;
    }
    const rightLen = n >>> 1;
    const leftLen = n - rightLen;
    const divisor = _pow95(rightLen);
    const left = value / divisor;
    const right = value % divisor;
    _fillRange(buf, start, start + leftLen, left);
    _fillRange(buf, start + leftLen, end, right);
}

/**
 * Unified book content function (feature flag: experimental).
 *
 * Every book's content is determined by its address in the text-address space.
 * The mapping is anchored to the player's story:
 *
 *   bookText(address) = addressToText(address - randomOrigin + playerRawAddress)
 *
 * At the player's book location (address = randomOrigin), this produces
 * the player's life story text exactly. Neighboring books differ by one
 * or two characters in the low-order positions.
 *
 * @param address - the book's address in the playable coordinate space
 * @param playerRawAddress - textToAddressFull(playerStoryText)
 * @param randomOrigin - the seed-derived origin
 * @param length - output string length (default CHARS_PER_BOOK)
 * @returns the book's full text
 */
export function unifiedBookText(
    address: bigint,
    playerRawAddress: bigint,
    randomOrigin: bigint,
    length: number = CHARS_PER_BOOK,
): string {
    const textAddress = address - randomOrigin + playerRawAddress;
    return addressToText(textAddress, length);
}

/* ---- Exports for solver/test use ---- */
export { LCG_A, LCG_C, LCG_A_INV, CHARSET_LEN };
export { packCoords, unpackCoords, mix32, unmix32, seedKey };
export { lcgNext, makeLCG };
