/** Invertible book coordinate encoding.
 *
 * The target book's content is generated by a simple LCG whose initial state
 * encodes the book's coordinates. A player who reads the source can:
 *
 *   1. Read a few characters from any page of a book
 *   2. Recover the LCG state from consecutive outputs
 *   3. Reverse the state back to coordinates using the known seed
 *
 * The mapping is:
 *   coords → state:  state = mixCoords(coords) XOR seedKey
 *   state → coords:  coords = unmixCoords(state XOR seedKey)
 *
 * mixCoords/unmixCoords are a simple invertible bit-shuffle so that nearby
 * coordinates don't produce obviously similar output.
 *
 * The LCG is deliberately weak — that's the point. It's a puzzle, not crypto.
 *
 * @module invertible.core
 */

import { hash } from "./prng.core.ts";
import { BOOKS_PER_GALLERY, CHARSET_SIZE, CHARS_PER_LINE, LINES_PER_PAGE, CHARS_PER_PAGE, CHARS_PER_BOOK, PAGES_PER_BOOK, FLOORS, POSITIONS_PER_SIDE } from "./scale.core.ts";
import { generateFullStoryBook } from "./book.core.ts";

/* ---- Constants ---- */

const CHARSET_LEN: number = CHARSET_SIZE;

/**
 * Early-exit threshold for textToAddress.
 *
 * When converting text to a base-95 number, most texts exceed the playable
 * address space within the first few characters. This threshold lets
 * textToAddress bail out early without computing the full (potentially
 * million-digit) number.
 *
 * Set to PLAYABLE_ADDRESS_MAX — if the running total exceeds the walkable
 * library, there's no point continuing. This fires after ~9 characters
 * for random text.
 *
 * @see PLAYABLE_ADDRESS_MAX — the actual library boundary
 */
export let TEXT_ADDRESS_EARLY_EXIT: bigint;  // initialized after PLAYABLE_ADDRESS_MAX

/** @deprecated Use PLAYABLE_ADDRESS_MAX for bounds checks, TEXT_ADDRESS_EARLY_EXIT for early-exit. */
export const LIBRARY_MAX: bigint = 95n ** 66n;

/**
 * Interpret a book's text as a base-95 number and return its true address.
 * Characters are treated as digits in [0, 94] (codepoint - 32).
 *
 * Exits early if the running value exceeds `limit` — since most texts blow
 * past the early-exit threshold within the first few characters, this is nearly free
 * for out-of-bounds books.
 *
 * @param text - the book's full text (or as much as needed)
 * @param limit - stop and return current value if it exceeds this
 * @returns the address (may exceed limit if text is in bounds)
 */
export function textToAddress(text: string, limit: bigint | null = TEXT_ADDRESS_EARLY_EXIT): bigint {
    let addr = 0n;
    for (let i = 0; i < text.length; i++) {
        addr = addr * 95n + BigInt(text.charCodeAt(i) - 32);
        if (limit !== null && addr > limit) return addr;
    }
    return addr;
}

/**
 * Returns true if a book's text-as-number falls within the walkable library.
 * False means the soul is damned — their book has no shelf location.
 */
export function isInBounds(text: string): boolean {
    return textToAddress(text) <= PLAYABLE_ADDRESS_MAX;
}

/**
 * Compute a soul's book address in the coordinate system anchored to the player.
 *
 * The library's "origin" is arbitrary. We pick it by anchoring to the player:
 *   bookAddress = rawAddress - playerRawAddress + playerBookAddress
 *
 * For the player themselves: rawAddress - rawAddress + playerBookAddress = playerBookAddress,
 * which is always within PLAYABLE_ADDRESS_MAX by construction.
 *
 * For NPCs: big number - big number + small number. Usually still enormous → damned.
 * By cosmic coincidence, an NPC whose rawAddress is close to the player's lands
 * within the library — their book genuinely exists here.
 *
 * @param rawAddress - textToAddress(storyText) for this soul, no early-exit limit
 * @param playerRawAddress - textToAddress(playerStoryText), no early-exit limit
 * @param playerBookAddress - a bigint in [0, PLAYABLE_ADDRESS_MAX], derived from game seed
 * @returns bookAddress — use isAddressInBounds() to check damnation
 */
export function computeBookAddress(
    rawAddress: bigint,
    playerRawAddress: bigint,
    playerBookAddress: bigint,
): bigint {
    return rawAddress - playerRawAddress + playerBookAddress;
}

/**
 * Returns true if a precomputed book address maps to a reachable library location.
 * Use this (not isInBounds) when you already have the address.
 */
export function isAddressInBounds(bookAddress: bigint): boolean {
    return bookAddress >= 0n && bookAddress <= PLAYABLE_ADDRESS_MAX;
}

export { POSITIONS_PER_SIDE } from "./scale.core.ts";

/**
 * The maximum address that maps to a sensible (walkable) library location.
 * playerBookAddress should be drawn from [0, PLAYABLE_ADDRESS_MAX].
 */
export const PLAYABLE_ADDRESS_MAX: bigint =
    POSITIONS_PER_SIDE * 2n * BigInt(FLOORS) * BigInt(BOOKS_PER_GALLERY); // position * sides * floors * booksPerGallery

// Now that PLAYABLE_ADDRESS_MAX is defined, set the early-exit threshold.
TEXT_ADDRESS_EARLY_EXIT = PLAYABLE_ADDRESS_MAX;

/**
 * Decompose a book address into library coordinates.
 * The address must be within [0, PLAYABLE_ADDRESS_MAX].
 *
 * Layout (innermost first):
 *   bookIndex : [0, booksPerGallery)
 *   floor     : [0, FLOORS-1]        — FLOORS floors
 *   side      : 0 or 1
 *   position  : [0, POSITIONS_PER_SIDE)
 *
 * @param addr - a bigint in [0, PLAYABLE_ADDRESS_MAX]
 * @param booksPerGallery - e.g. 200 (from scale.core.ts)
 * @returns BookCoords
 */
export function addressToCoords(addr: bigint, booksPerGallery: number): { side: number; position: bigint; floor: bigint; bookIndex: number } {
    const bpg = BigInt(booksPerGallery);
    const bookIndex = Number(addr % bpg);
    addr = addr / bpg;

    const _FLOORS = BigInt(FLOORS);
    const floor = addr % _FLOORS;
    addr = addr / _FLOORS;

    const side = Number(addr % 2n);
    const position = addr / 2n; // [0, POSITIONS_PER_SIDE)

    return { side, position, floor, bookIndex };
}

/**
 * Pack library coordinates into a flat address.
 * Inverse of addressToCoords.
 */
export function coordsToAddress(side: number, position: bigint, floor: bigint, bookIndex: number): bigint {
    const bpg = BigInt(BOOKS_PER_GALLERY);
    const _FLOORS = BigInt(FLOORS);
    return BigInt(bookIndex) + bpg * (floor + _FLOORS * (BigInt(side) + 2n * position));
}

/** LCG parameters (mod 2^32). Multiplier from Numerical Recipes. */
const LCG_A: number = 1664525;
const LCG_C: number = 1013904223;

/* ---- Exported interfaces ---- */

/** Unpacked book coordinates. */
export interface BookCoords {
    side: number;
    position: number;
    floor: number;
    bookIndex: number;
}

/** LCG stream with alternating even/odd chains. */
export interface LCGStream {
    nextInt(n: number): number;
    state(): [number, number];
}

/* ---- Invertible coordinate encoding ---- */

/**
 * Pack coordinates into a single 64-bit-ish pair of 32-bit words.
 * Layout:
 *   word0: (side << 31) | ((floor & 0x7FFF) << 16) | (bookIndex & 0xFFFF)
 *   word1: position as signed int32 (reinterpreted as uint32)
 */
function packCoords(side: number, position: number, floor: number, bookIndex: number): [number, number] {
    const w0 = ((side & 1) << 31) | ((floor & 0x7FFF) << 16) | (bookIndex & 0xFFFF);
    const w1 = position | 0; // signed → int32 bits
    return [w0 >>> 0, w1 >>> 0];
}

function unpackCoords(w0: number, w1: number): BookCoords {
    const side = (w0 >>> 31) & 1;
    const floor = (w0 >>> 16) & 0x7FFF;
    const bookIndex = w0 & 0xFFFF;
    const position = w1 | 0; // reinterpret as signed
    return { side, position, floor, bookIndex };
}

/**
 * Invertible 32-bit mix (based on splitmix32 finalizer).
 * Each step is reversible.
 */
function mix32(x: number): number {
    x = x >>> 0;
    x ^= x >>> 16;
    x = Math.imul(x, 0x45d9f3b);
    x ^= x >>> 16;
    x = Math.imul(x, 0x45d9f3b);
    x ^= x >>> 16;
    return x >>> 0;
}

/** Inverse of mix32. */
function unmix32(x: number): number {
    x = x >>> 0;
    x ^= x >>> 16;
    x = Math.imul(x, 0x119de1f3); // modular inverse of 0x45d9f3b mod 2^32
    x ^= x >>> 16;
    x = Math.imul(x, 0x119de1f3);
    x ^= x >>> 16;
    return x >>> 0;
}

/**
 * Derive a 2-word key from the global seed string.
 * This is what the player needs to know (it's just hash(seed + suffix)).
 */
function seedKey(globalSeed: string): [number, number] {
    return [hash(globalSeed + ":inv0"), hash(globalSeed + ":inv1")];
}

/**
 * Encode coordinates into a 2-word LCG state.
 *
 * coords → pack → mix each word → XOR with seed key
 *
 * @param {number} side
 * @param {number} position
 * @param {number} floor
 * @param {number} bookIndex
 * @param {string} globalSeed
 * @returns {[number, number]} two uint32 state words
 */
export function encodeCoords(side: number, position: number, floor: number, bookIndex: number, globalSeed: string): [number, number] {
    const [w0, w1] = packCoords(side, position, floor, bookIndex);
    const [k0, k1] = seedKey(globalSeed);
    return [(mix32(w0) ^ k0) >>> 0, (mix32(w1) ^ k1) >>> 0];
}

/**
 * Decode a 2-word state back to coordinates.
 *
 * state → XOR with seed key → unmix each word → unpack
 *
 * @param {number} s0
 * @param {number} s1
 * @param {string} globalSeed
 * @returns {{ side, position, floor, bookIndex }}
 */
export function decodeCoords(s0: number, s1: number, globalSeed: string): BookCoords {
    const [k0, k1] = seedKey(globalSeed);
    const w0 = unmix32((s0 ^ k0) >>> 0);
    const w1 = unmix32((s1 ^ k1) >>> 0);
    return unpackCoords(w0, w1);
}

/* ---- LCG ---- */

/** Advance LCG state by one step. */
function lcgNext(s: number): number {
    return (Math.imul(LCG_A, s) + LCG_C) >>> 0;
}

/** Reverse LCG state by one step. */
// LCG_A_INV is the modular inverse of LCG_A mod 2^32.
const LCG_A_INV: number = 4276115653; // computed: LCG_A * LCG_A_INV ≡ 1 (mod 2^32)
export function lcgPrev(s: number): number {
    return Math.imul((s - LCG_C) >>> 0, LCG_A_INV) >>> 0;
}

/**
 * Create an LCG stream from a 2-word state.
 * s0 is the running LCG state. s1 is mixed in once at the start via XOR,
 * giving 64 bits of effective key space while keeping a simple 32-bit LCG
 * that's easy to reverse from output.
 *
 * Two independent LCGs read in alternation: even chars from s0, odd from s1.
 */
function makeLCG(s0: number, s1: number): LCGStream {
    let a = s0 >>> 0, b = s1 >>> 0;
    let even = true;
    return {
        nextInt(n: number): number {
            if (even) {
                a = lcgNext(a);
                even = false;
                return a % n;
            } else {
                b = lcgNext(b);
                even = true;
                return b % n;
            }
        },
        state(): [number, number] { return [a, b]; }
    };
}

/* ---- Page generation ---- */

/**
 * Generate a page of a book using the invertible LCG.
 * The state is derived from coordinates + seed, and can be reversed.
 *
 * @param {number} side
 * @param {number} position
 * @param {number} floor
 * @param {number} bookIndex
 * @param {number} pageIndex - 0-based
 * @param {string} globalSeed
 * @returns {string}
 */
export function generateTargetPage(side: number, position: number, floor: number, bookIndex: number, pageIndex: number, globalSeed: string): string {
    const [s0, s1] = encodeCoords(side, position, floor, bookIndex, globalSeed);

    // Advance LCG past prior pages to maintain determinism.
    const charsPerPage = LINES_PER_PAGE * CHARS_PER_LINE;
    const skipCalls = pageIndex * charsPerPage;
    const skipPerChain = Math.floor(skipCalls / 2);
    const extraEven = skipCalls % 2;

    let a = s0, b = s1;
    for (let i = 0; i < skipPerChain + extraEven; i++) a = lcgNext(a);
    for (let i = 0; i < skipPerChain; i++) b = lcgNext(b);

    const lcg = makeLCG(a, b);
    const lines: string[] = [];
    for (let l = 0; l < LINES_PER_PAGE; l++) {
        let line = "";
        for (let c = 0; c < CHARS_PER_LINE; c++) {
            line += String.fromCharCode(32 + lcg.nextInt(CHARSET_LEN));
        }
        lines.push(line);
    }
    return lines.join("\n");
}

/**
 * Recover coordinates from consecutive output characters of a book page.
 *
 * Requires at least 10 consecutive characters from the START of page 0.
 * (5 per chain → ~32.8 bits of constraint, uniquely pins each 32-bit state.)
 *
 * @param {string} chars - at least 10 characters from the beginning of page 0
 * @param {string} globalSeed
 * @returns {{ side, position, floor, bookIndex } | null}
 */
export function recoverCoords(chars: string, globalSeed: string): BookCoords | null {
    if (chars.length < 10) return null;

    const v: number[] = [];
    for (let i = 0; i < chars.length && i < 12; i++) {
        v.push(chars.charCodeAt(i) - 32);
    }

    const evenTargets: number[] = [];
    for (let i = 0; i < v.length; i += 2) evenTargets.push(v[i]);

    const oddTargets: number[] = [];
    for (let i = 1; i < v.length; i += 2) oddTargets.push(v[i]);

    const foundS0 = recoverOneChain(evenTargets);
    if (foundS0 === null) return null;

    const foundS1 = recoverOneChain(oddTargets);
    if (foundS1 === null) return null;

    return decodeCoords(foundS0, foundS1, globalSeed);
}

/**
 * Recover the initial state of one LCG chain given consecutive outputs mod 95.
 * targets[0] = lcgNext(s) % 95, targets[1] = lcgNext^2(s) % 95, etc.
 * Returns s, or null if no match.
 */
function recoverOneChain(targets: number[]): number | null {
    if (targets.length < 2) return null;

    for (let a = targets[0]; a < 0x100000000; a += CHARSET_LEN) {
        let match = true;
        let cur = a;
        for (let i = 1; i < targets.length; i++) {
            cur = lcgNext(cur);
            if (cur % CHARSET_LEN !== targets[i]) { match = false; break; }
        }
        if (match) return lcgPrev(a);
    }
    return null;
}

/* ---- Full-precision address computation ---- */

const _pow95Cache: Map<number, bigint> = new Map();
function _pow95(n: number): bigint {
    let p = _pow95Cache.get(n);
    if (p === undefined) {
        p = 95n ** BigInt(n);
        _pow95Cache.set(n, p);
    }
    return p;
}

function _convertRange(codes: Int32Array, start: number, end: number): bigint {
    const n = end - start;
    if (n === 0) return 0n;
    if (n === 1) return BigInt(codes[start]);
    if (n === 2) return BigInt(codes[start]) * 95n + BigInt(codes[start + 1]);
    const mid = start + (n >>> 1);
    return _convertRange(codes, start, mid) * _pow95(end - mid) + _convertRange(codes, mid, end);
}

/**
 * Full-precision textToAddress using divide-and-conquer base conversion.
 * O(n log²n) vs O(n²) for the naive Horner's method.
 *
 * Computes the true base-95 address of the full text without any early exit.
 * For 1,312,000 characters this produces a ~2.6 million digit number in ~300ms.
 *
 * Use this for verification and testing, not in hot loops.
 */
export function textToAddressFull(text: string): bigint {
    const codes = new Int32Array(text.length);
    for (let i = 0; i < text.length; i++) codes[i] = text.charCodeAt(i) - 32;
    return _convertRange(codes, 0, codes.length);
}

/* ---- Inverse: address → text (D&C) ---- */

/**
 * Convert a bigint address back to a base-95 string of the given length.
 * D&C approach: divmod by 95^(n/2) splits the string into left and right
 * halves, same complexity class as textToAddressFull.
 *
 * @param addr - the bigint address
 * @param length - output string length (default CHARS_PER_BOOK)
 * @returns the base-95 decoded string
 */
export function addressToText(addr: bigint, length: number = CHARS_PER_BOOK): string {
    if (addr < 0n) throw new RangeError("addressToText: address must be non-negative");
    const buf = new Uint8Array(length);
    _fillRange(buf, 0, length, addr);
    // Convert digit values to characters
    let s = "";
    for (let i = 0; i < length; i++) s += String.fromCharCode(buf[i] + 32);
    return s;
}

function _fillRange(buf: Uint8Array, start: number, end: number, value: bigint): void {
    const n = end - start;
    if (n === 0) return;
    if (n === 1) {
        buf[start] = Number(value % 95n);
        return;
    }
    if (n === 2) {
        buf[start + 1] = Number(value % 95n);
        buf[start] = Number((value / 95n) % 95n);
        return;
    }
    const rightLen = n >>> 1;
    const leftLen = n - rightLen;
    const divisor = _pow95(rightLen);
    const left = value / divisor;
    const right = value % divisor;
    _fillRange(buf, start, start + leftLen, left);
    _fillRange(buf, start + leftLen, end, right);
}

/**
 * Unified book content function (feature flag: experimental).
 *
 * Every book's content is determined by its address in the text-address space.
 * The mapping is anchored to the player's story:
 *
 *   bookText(address) = addressToText(address - playerBookAddress + playerRawAddress)
 *
 * At the player's book location (address = playerBookAddress), this produces
 * the player's life story text exactly. Neighboring books differ by one
 * or two characters in the low-order positions.
 *
 * @param address - the book's address in the playable coordinate space
 * @param playerRawAddress - textToAddressFull(playerStoryText)
 * @param playerBookAddress - the seed-derived origin
 * @param length - output string length (default CHARS_PER_BOOK)
 * @returns the book's full text
 */
export function unifiedBookText(
    address: bigint,
    playerRawAddress: bigint,
    playerBookAddress: bigint,
    length: number = CHARS_PER_BOOK,
): string {
    const textAddress = address - playerBookAddress + playerRawAddress;
    return addressToText(textAddress, length);
}

/* ---- Feistel permutation over address space ---- */

const FEISTEL_ROUNDS = 4;
// Round up to next even bit width that covers PLAYABLE_ADDRESS_MAX
const FEISTEL_BITS = 60; // 2^60 > PLAYABLE_ADDRESS_MAX ≈ 4e17
const FEISTEL_HALF = FEISTEL_BITS >>> 1; // 30
const FEISTEL_MASK = (1n << BigInt(FEISTEL_HALF)) - 1n; // 0x3FFFFFFF
const FEISTEL_DOMAIN = 1n << BigInt(FEISTEL_BITS); // 2^60

/** Derive 4 round subkeys from the game seed. */
export function feistelKey(globalSeed: string): Uint32Array {
    const key = new Uint32Array(FEISTEL_ROUNDS);
    for (let i = 0; i < FEISTEL_ROUNDS; i++) {
        key[i] = hash(globalSeed + ":feistel:" + i);
    }
    return key;
}

/** Feistel round function: hash the right half with the round subkey. */
function feistelRound(half: bigint, subkey: number): bigint {
    // Mix the 30-bit half with the subkey via hash
    const h = hash(subkey + ":" + half.toString(36));
    return BigInt(h) & FEISTEL_MASK;
}

/** Raw 4-round Feistel on 2^60 domain (no cycle walking). */
function feistelRaw(addr: bigint, key: Uint32Array): bigint {
    let left = (addr >> BigInt(FEISTEL_HALF)) & FEISTEL_MASK;
    let right = addr & FEISTEL_MASK;
    for (let i = 0; i < FEISTEL_ROUNDS; i++) {
        const newLeft = right;
        right = left ^ feistelRound(right, key[i]);
        left = newLeft;
    }
    return (left << BigInt(FEISTEL_HALF)) | right;
}

/** Raw inverse Feistel (rounds in reverse). */
function feistelRawInverse(addr: bigint, key: Uint32Array): bigint {
    let left = (addr >> BigInt(FEISTEL_HALF)) & FEISTEL_MASK;
    let right = addr & FEISTEL_MASK;
    for (let i = FEISTEL_ROUNDS - 1; i >= 0; i--) {
        const newRight = left;
        left = right ^ feistelRound(left, key[i]);
        right = newRight;
    }
    return (left << BigInt(FEISTEL_HALF)) | right;
}

/**
 * Bijective permutation over [0, PLAYABLE_ADDRESS_MAX] using cycle-walking Feistel.
 * Adjacent inputs scatter to distant outputs. The player's origin still cancels
 * in the unified content formula.
 */
export function permute(addr: bigint, key: Uint32Array): bigint {
    let result = addr;
    do {
        result = feistelRaw(result, key);
    } while (result > PLAYABLE_ADDRESS_MAX);
    return result;
}

/** Inverse of permute — recovers the original address. */
export function unpermute(addr: bigint, key: Uint32Array): bigint {
    let result = addr;
    do {
        result = feistelRawInverse(result, key);
    } while (result > PLAYABLE_ADDRESS_MAX);
    return result;
}

/* ---- Per-page extraction ---- */

/**
 * Extract a single page from a text-space bigint address.
 *
 * Page K occupies character positions [K*CHARS_PER_PAGE, (K+1)*CHARS_PER_PAGE)
 * in the base-95 representation. Extracts those digits via divmod without
 * converting the entire 1,312,000-character book.
 *
 * @param addr - text-space bigint (the full ~2.6M-digit number)
 * @param pageIndex - 0-based page number [0, 409]
 * @param totalLength - total book length in characters (default CHARS_PER_BOOK)
 * @returns 3200-character string for the requested page
 */
export function extractPage(addr: bigint, pageIndex: number, totalLength: number = CHARS_PER_BOOK): string {
    const pageSize = CHARS_PER_PAGE;
    // Digits to the right of this page
    const rightChars = totalLength - (pageIndex + 1) * pageSize;
    if (rightChars < 0) throw new RangeError("pageIndex out of range");

    // Shift right to remove digits below this page
    let pageValue: bigint;
    if (rightChars === 0) {
        pageValue = addr % _pow95(pageSize);
    } else {
        const shifted = addr / _pow95(rightChars);
        pageValue = shifted % _pow95(pageSize);
    }

    return addressToText(pageValue, pageSize);
}

/* ---- Unified + Feistel integration ---- */

/**
 * Unified book content with Feistel permutation.
 *
 * Returns one page of a book at the given shelf address. At the player's
 * origin, the content is the player's life-story book (extracted from
 * playerRawAddress via the base-95 bijection). Everywhere else, the
 * Feistel-permuted address seeds a PRNG that generates pseudorandom
 * printable ASCII — the same "symbol slop" as generateBookPage but
 * derived from the unified address space.
 *
 * The branch is minimal: one address comparison per call. The content
 * derivation uses the same character set and page format either way.
 *
 * @param address - shelf address in [0, PLAYABLE_ADDRESS_MAX]
 * @param playerRawAddress - textToAddressFull of the player's full book text
 * @param playerBookAddress - seed-derived origin address
 * @param key - Feistel key from feistelKey(seed)
 * @param pageIndex - 0-based page number [0, 409]
 * @returns CHARS_PER_PAGE-character page string
 */
export function unifiedBookPage(
    address: bigint,
    playerRawAddress: bigint,
    playerBookAddress: bigint,
    key: Uint32Array,
    pageIndex: number,
): string {
    if (address === playerBookAddress) {
        // Player's book — extract from the true base-95 bijection
        return extractPage(playerRawAddress, pageIndex);
    }
    // All other books — Feistel-scrambled PRNG noise
    const scrambled = permute(address, key);
    return _generateNoisePage(scrambled, pageIndex);
}

/** Generate a page of PRNG noise from a scrambled address + page index. */
function _generateNoisePage(scrambled: bigint, pageIndex: number): string {
    // Seed from the scrambled address and page index
    const seedStr = scrambled.toString(36) + ":p" + pageIndex;
    const rng = _miniRng(hash(seedStr), hash(seedStr + ":1"));
    let page = "";
    for (let i = 0; i < CHARS_PER_PAGE; i++) {
        page += String.fromCharCode(32 + (rng() % CHARSET_LEN));
    }
    return page;
}

/** Minimal xorshift64 PRNG from two 32-bit seeds. */
function _miniRng(s0: number, s1: number): () => number {
    let a = s0 >>> 0, b = s1 >>> 0;
    return () => {
        let t = a;
        const s = b;
        a = s;
        t ^= t << 23;
        t ^= t >>> 17;
        t ^= s;
        t ^= s >>> 26;
        b = t;
        return (t >>> 0);
    };
}

/* ---- Carry-free digit-wise embedding ---- */

/**
 * Fast integer hash for counter-mode PRNG.
 * Mixes a 32-bit counter with two 32-bit seed words.
 * Based on splitmix32 / Wang hash.
 */
function counterHash(counter: number, seedLo: number, seedHi: number): number {
    let x = (counter + seedLo) >>> 0;
    x ^= seedHi;
    x ^= x >>> 16;
    x = Math.imul(x, 0x45d9f3b);
    x ^= x >>> 16;
    x = Math.imul(x, 0x45d9f3b);
    x ^= x >>> 16;
    return x >>> 0;
}

/**
 * Split a bigint seed into two 32-bit words for counterHash.
 */
function seedWords(seed: bigint): [number, number] {
    const lo = Number(seed & 0xFFFFFFFFn);
    const hi = Number((seed >> 32n) & 0xFFFFFFFFn);
    return [lo, hi];
}

/** Digits per hash call. 95^4 = 81,450,625 < 2^32, so 4 base-95 digits fit. */
const DIGITS_PER_HASH = 4;

/**
 * Seekable expansion function: returns `count` pseudorandom digits in [0, 94],
 * seeded from `seed` (bigint), starting at character position `offset`.
 *
 * Counter-mode: positions [4k, 4k+3] derive from counterHash(k, seedLo, seedHi),
 * decomposed into 4 base-95 digits. Deterministic and seekable.
 */
export function expand(seed: bigint, offset: number, count: number): Uint8Array {
    const [lo, hi] = seedWords(seed);
    const out = new Uint8Array(count);

    let i = 0;
    const startBlock = (offset / DIGITS_PER_HASH) | 0;
    const startLane = offset - startBlock * DIGITS_PER_HASH;

    // Handle partial first block if offset isn't block-aligned
    if (startLane > 0 && count > 0) {
        let h = counterHash(startBlock, lo, hi);
        for (let d = 0; d < startLane; d++) h = (h / 95) | 0;
        for (let d = startLane; d < DIGITS_PER_HASH && i < count; d++, i++) {
            out[i] = h % 95;
            h = (h / 95) | 0;
        }
    }

    // Process full blocks of 4
    let block = startBlock + (startLane > 0 ? 1 : 0);
    while (i + DIGITS_PER_HASH <= count) {
        let h = counterHash(block, lo, hi);
        out[i]     = h % 95; h = (h / 95) | 0;
        out[i + 1] = h % 95; h = (h / 95) | 0;
        out[i + 2] = h % 95; h = (h / 95) | 0;
        out[i + 3] = h % 95;
        i += DIGITS_PER_HASH;
        block++;
    }

    // Handle partial last block
    if (i < count) {
        let h = counterHash(block, lo, hi);
        while (i < count) {
            out[i] = h % 95;
            h = (h / 95) | 0;
            i++;
        }
    }

    return out;
}

/**
 * Expand permute(playerBookAddress) over all 1,312,000 positions.
 * Computed once at game start and cached.
 */
export function buildOriginPad(playerBookAddress: bigint, key: Uint32Array): Uint8Array {
    const permuted = permute(playerBookAddress, key);
    return expand(permuted, 0, CHARS_PER_BOOK);
}

/**
 * Materialize the player's full book as digit values (charCode - 32).
 * Computed once at game start and cached.
 */
export function buildPlayerDigits(storyText: string, fields: { name: string; occupation: string; hometown: string; causeOfDeath: string }): Uint8Array {
    const fullBook: string = generateFullStoryBook(storyText, fields);
    const digits = new Uint8Array(CHARS_PER_BOOK);
    for (let i = 0; i < fullBook.length; i++) {
        digits[i] = fullBook.charCodeAt(i) - 32;
    }
    return digits;
}

/**
 * Unified book content function — no branch.
 *
 * For any address (including the player's), the content is:
 *   digit(i) = (expand(permute(address), i) - originPad[i] + playerDigits[i]) mod 95
 *
 * At the player's address, permute(address) === permute(origin), so expand
 * terms cancel, leaving playerDigits — the player's book exactly.
 *
 * @param address - shelf address in [0, PLAYABLE_ADDRESS_MAX]
 * @param originPad - precomputed expand(permute(playerBookAddress)) for all positions
 * @param playerDigits - precomputed player book digit values (charCode - 32)
 * @param key - Feistel key from feistelKey(seed)
 * @param pageIndex - 0-based page number [0, 409]
 * @returns page string, line-broken at CHARS_PER_LINE
 */
export function digitWiseBookPage(
    address: bigint,
    originPad: Uint8Array,
    playerDigits: Uint8Array,
    key: Uint32Array,
    pageIndex: number,
): string {
    const scrambled = permute(address, key);
    const pageOffset = pageIndex * CHARS_PER_PAGE;
    const addrDigits = expand(scrambled, pageOffset, CHARS_PER_PAGE);

    const lines: string[] = [];
    for (let l = 0; l < LINES_PER_PAGE; l++) {
        let line = "";
        for (let c = 0; c < CHARS_PER_LINE; c++) {
            const i = l * CHARS_PER_LINE + c;
            const d = ((addrDigits[i] - originPad[pageOffset + i] + playerDigits[pageOffset + i]) % CHARSET_SIZE + CHARSET_SIZE) % CHARSET_SIZE;
            line += String.fromCharCode(32 + d);
        }
        lines.push(line);
    }
    return lines.join("\n");
}

/* ---- Exports for solver/test use ---- */
export { LCG_A, LCG_C, LCG_A_INV, CHARSET_LEN };
export { packCoords, unpackCoords, mix32, unmix32, seedKey };
export { lcgNext, makeLCG };
